export const routeCenterScreenTestIDs = Object.freeze({
  TabbedHeaderPager:'TabbedHeaderPagerDemoID',
  TabbedHeaderList:'TabbedHeaderListDemoID',
  DetailsHeaderScrollView:'DetailsHeaderScrollViewDemoID',
  DetailsHeaderFlatList:'DetailsHeaderFlatListDemoID',
  DetailsHeaderSectionList:'DetailsHeaderSectionListDemoID',
  AvatarHeaderScrollView:'AvatarHeaderScrollViewDemoID',
  AvatarHeaderFlatList:'AvatarHeaderFlatListDemoID',
  AvatarHeaderSectionList:'AvatarHeaderSectionListDemoID',
  StickyHeaderScrollView:'StickyHeaderScrollViewDemoID',
  StickyHeaderFlatList:'StickyHeaderFlatListDemoID',
  StickyHeaderSectionList:'StickyHeaderSectionListDemoID',
  TabbedHeaderFlashList:'TabbedHeaderFlashListDemoID',
  AvatarHeaderFlashList:'AvatarHeaderFlashListDemoID',
  DetailsHeaderFlashListDemo:'DetailsHeaderFlashListDemoID',
  StickyHeaderFlashListDemo:'StickyHeaderFlashListDemoID',
  StickyParallaxHeader: 'StickyParallaxHeaderTestID',
  headerTitle: 'HeaderTitleTestID',
  popularQuizesTab: 'PopularQuizesTabTestID',
  popularQuizesHeader: 'PopularQuizesHeaderTestID',
  productDesignTab: 'ProductDesignTabTestID',
  productDesignHeader: 'ProductDesignHeaderTestID',
  developmentTab: 'DevelopmentTabTestID',
  developmentHeader: 'DevelopmentHeaderTestID',
  projectManagementTab: 'ProjectManagementTabTestID',
  projectManagementHeader: 'ProjectManagementHeaderTestID',
  yodaLink: 'YodaLinkTestID',
  simsLink: 'SimsLinkTestID',
  stickyHeaderFlatListLink: 'StickyHeaderFlatListLinkTestID',
  stickyHeaderScrollViewLink: 'StickyHeaderScrollViewLinkTestID',
  stickyHeaderSectionListLink: 'StickyHeaderSectionListLinkTestID',
  tabbedHeaderListLink: 'TabbedHeaderListLinkTestID',
  tabbedHeaderPagerLink: 'TabbedHeaderPagerLinkTestID',
  avatarHeaderFlatListLink: 'AvatarHeaderFlatListLinkTestID',
  avatarHeaderScrollViewLink: 'AvatarHeaderScrollViewLinkTestID',
  avatarHeaderSectionListLink: 'AvatarHeaderSectionListLinkTestID',
  detailsHeaderFlatListLink: 'DetailsHeaderFlatListLinkTestID',
  detailsHeaderScrollViewLink: 'DetailsHeaderScrollViewLinkTestID',
  detailsHeaderSectionListLink: 'DetailsHeaderSectionListLinkTestID',
  tabbedHeaderWithSectionListsLink: 'TabbedHeaderWithSectionListsLinkTestID',
  tabbedHeaderFlashListLink: 'TabbedHeaderFlashListLinkTestID',
  avatarHeaderFlashListLink: 'AvatarHeaderFlashListLinkTestID',
  detailsHeaderFlashListLink: 'DetailsHeaderFlashListLinkTestID',
  stickyHeaderFlashListLink: 'StickyHeaderFlashListLinkTestID',
  tabbedHeaderWithAnimatedColorsLink: 'TabbedHeaderWithAnimatedColorsLinkTestID',
});
